ci: upgrade workflows

diff --git a/.github/workflows/tests-linux.yml b/.github/workflows/tests-linux.yml
--- a/.github/workflows/tests-linux.yml
+++ b/.github/workflows/tests-linux.yml
@@ -1,24 +1,28 @@
 name: Run tests for Linux
+
 on:
-  workflow_dispatch:
+  # Allow being called by other workflows
   workflow_call:
+  # Allow being called manually
+  workflow_dispatch:
 
 jobs:
-  test_linux:
+  flutter_test:
+    name: Run Tests
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v2
-      - uses: subosito/flutter-action@v1.5.0
+      - uses: actions/checkout@v3
+      - uses: subosito/flutter-action@v2
 
       - name: Setup
         run: |
-          flutter upgrade
+          flutter upgrade --force
           flutter pub get
-
-      - name: Download artifacts
-        uses: actions/download-artifact@v3
-        with:
-          path: artifacts
-
+        
       - name: Run tests
         run: flutter test
+        
+      - name: Print directory structure
+        # Ensure this step runs even after a failure, but not when cancelled.
+        if: success() || failure()
+        run: tree -a
